### ISSUE TITLE
Example Flow to test PRs

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-red#12]
In order to review the recent PRs, I was going to develop an example application that uses all the features. This will fix #7 and simplify the review process. However, given that @hidetak you are working on this, you probably already have such applications (like in your video). Can you submit this as a separate PR and we ideally update the example each time we add new features? I am open to suggestions on how to better review PRs for node-red since there is a bit more testing involved for the reviewer due to dragging buttons around

**Comment by hidetak** [comment]
@egekorkan 

Thank you for your response.
I will try to provide an example of the flow.
I am not sure if the configuration values can be reflected well in the example flow because some of the node settings are credential.
If it does not reflect well, I will try to modify it to include the node.

I will also think about how to review it.
If you review the node, would it be sufficient to check the server flow and the client flow on your PC at a minimum?

**Comment by egekorkan** [comment]
> If you review the node, would it be sufficient to check the server flow and the client flow on your PC at a minimum?

Thinking of the workflow, what I currently have is one Flow that has both but I think it would be better in the future to have two flows like you mentioned, client and server.

**Comment by hidetak** [comment]
@egekorkan 

I have added an example server and client flows.
The example flows can be loaded and run from the Import menu of the Node-RED editor.

<img width="959" alt="image" src="https://github.com/eclipse-thingweb/node-red/assets/39742000/0f4c6989-8973-4100-9c7e-16aebc276234">

This will make it easier to check how the nodes are working.

**Comment by egekorkan** [comment]
Done via #8
